#!/usr/bin/env bash
# ==============================================================================
# scan_project.sh — Scan project tree and generate Makefile.mk files
#
# Usage: bash scripts/scan_project.sh [root_dir]
#
# For each directory that contains recognised source files, the script creates
# (or updates) a Makefile.mk that uses GNU make's $(wildcard …) function to
# discover sources at build time — so adding or removing files within an
# existing directory is picked up automatically on the next 'make' invocation.
#
# Re-run this script (or 'make scan') when you add a NEW source directory.
#
# Recognised extensions:
#   C           : .c
#   C++         : .cpp  .cxx  .cc
#   VHDL        : .vhd  .vhdl
#   Verilog/SV  : .v    .sv
#   Assembly    : .s    .S    .asm
# ==============================================================================

set -euo pipefail

ROOT="${1:-.}"
ROOT="$(realpath "$ROOT")"

# Directories to exclude from the scan
EXCLUDE_PATTERNS=(
    ".git"
    "build"
    "make"
    "templates"
    "scripts"
    "__pycache__"
    "node_modules"
    ".cache"
)

# Source file extensions to detect
SOURCE_EXTS=( "*.c" "*.cpp" "*.cxx" "*.cc" "*.vhd" "*.vhdl" "*.v" "*.sv" "*.s" "*.S" "*.asm" )

CREATED=0
UPDATED=0
SKIPPED=0

# ── Helpers ──────────────────────────────────────────────────────────────────

log()  { printf '[SCAN] %s\n' "$*"; }
info() { printf '[SCAN]   %s\n' "$*"; }

# Returns 0 if the directory contains at least one recognised source file
dir_has_sources() {
    local dir="$1"
    local ext files
    for ext in "${SOURCE_EXTS[@]}"; do
        # Using nullglob to avoid literal glob when no match
        shopt -s nullglob
        files=( "$dir"/$ext )
        shopt -u nullglob
        [[ ${#files[@]} -gt 0 ]] && return 0
    done
    return 1
}

# Returns 0 if the directory path contains an excluded pattern component
dir_is_excluded() {
    local dir="$1"
    local rel pattern
    rel="${dir#$ROOT/}"   # strip root prefix for matching
    for pattern in "${EXCLUDE_PATTERNS[@]}"; do
        # Match the pattern as a path component anywhere in the relative path
        if [[ "/$rel/" == *"/$pattern/"* || "$rel" == "$pattern" || "$rel" == "$pattern/"* ]]; then
            return 0
        fi
    done
    return 1
}

# Generate or update a Makefile.mk for the given directory
generate_makefile_mk() {
    local dir="$1"
    local outfile="$dir/Makefile.mk"

    # ── Build the file content ────────────────────────────────────────────────
    # _THIS_DIR captures the directory of THIS Makefile.mk when it is included.
    # Because C_SRCS (etc.) are initialised with := in the root Makefile,
    # the $(wildcard …) on the += lines expands immediately at parse time,
    # giving a fresh file list on every 'make' invocation without re-scanning.
    local content
    content=$(cat <<'TEMPLATE'
# ==============================================================================
# Auto-generated by scripts/scan_project.sh — DO NOT EDIT manually.
# Delete with 'make distclean' and regenerate with 'make scan'.
#
# Source lists refresh automatically on every 'make' invocation via $(wildcard).
# Re-run 'make scan' only when a new source DIRECTORY is added.
# ==============================================================================

# Capture this file's directory at include time
_THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

# C sources
C_SRCS    += $(wildcard $(_THIS_DIR)*.c)

# C++ sources
CXX_SRCS  += $(wildcard $(_THIS_DIR)*.cpp $(_THIS_DIR)*.cxx $(_THIS_DIR)*.cc)

# VHDL sources
VHDL_SRCS += $(wildcard $(_THIS_DIR)*.vhd $(_THIS_DIR)*.vhdl)

# Verilog / SystemVerilog sources
V_SRCS    += $(wildcard $(_THIS_DIR)*.v $(_THIS_DIR)*.sv)

# Assembly sources
ASM_SRCS  += $(wildcard $(_THIS_DIR)*.s $(_THIS_DIR)*.S $(_THIS_DIR)*.asm)
TEMPLATE
)

    # ── Write only if content changed (avoid touching timestamps) ─────────────
    if [[ -f "$outfile" ]]; then
        if [[ "$(cat "$outfile")" == "$content" ]]; then
            (( SKIPPED++ )) || true
            return
        fi
        printf '%s\n' "$content" > "$outfile"
        info "Updated:  ${outfile#$ROOT/}"
        (( UPDATED++ )) || true
    else
        printf '%s\n' "$content" > "$outfile"
        info "Created:  ${outfile#$ROOT/}"
        (( CREATED++ )) || true
    fi
}

# ── Main scan ────────────────────────────────────────────────────────────────

log "Scanning: $ROOT"
log "──────────────────────────────────────────────────────"

# Collect all directories (sorted for reproducibility)
while IFS= read -r -d '' dir; do
    # Skip excluded paths
    dir_is_excluded "$dir" && continue

    # Only process directories with source files
    dir_has_sources "$dir" && generate_makefile_mk "$dir"

done < <(find "$ROOT" -type d -print0 | sort -z)

log "──────────────────────────────────────────────────────"
log "Created: $CREATED  |  Updated: $UPDATED  |  Unchanged: $SKIPPED"
log "Done."
