#!/usr/bin/env bash
# ==============================================================================
# scan_project.sh — Scan project tree and generate Makefile.mk files
#
# Usage: bash scripts/scan_project.sh [root_dir]
#
# For each directory that contains recognised source files, the script:
#   1. Creates/updates Makefile.mk  — uses $(wildcard) for C/C++/ASM/Verilog
#                                     uses .compile_order for VHDL if present
#   2. Creates .compile_order       — VHDL directories only; NEVER overwritten
#                                     once created (preserves user edits)
#
# .compile_order format:
#   One filename per line (no paths), # comments, blank lines ignored.
#   Edit it to set the exact VHDL compilation order required by your design.
#   Re-run 'make scan' only when a new source DIRECTORY is added.
#
# Recognised extensions:
#   C           : .c
#   C++         : .cpp  .cxx  .cc
#   VHDL        : .vhd  .vhdl
#   Verilog/SV  : .v    .sv
#   Assembly    : .s    .S    .asm
# ==============================================================================

set -euo pipefail

ROOT="${1:-.}"
ROOT="$(realpath "$ROOT")"

EXCLUDE_PATTERNS=(
    ".git" "build" "make" "templates" "scripts"
    "__pycache__" "node_modules" ".cache"
)

SOURCE_EXTS=( "*.c" "*.cpp" "*.cxx" "*.cc" "*.vhd" "*.vhdl" "*.v" "*.sv" "*.s" "*.S" "*.asm" )
VHDL_EXTS=(   "*.vhd" "*.vhdl" )

MK_CREATED=0;  MK_UPDATED=0;  MK_SKIPPED=0
ORD_CREATED=0; ORD_SKIPPED=0

log()  { printf '[SCAN] %s\n' "$*"; }
info() { printf '[SCAN]   %s\n' "$*"; }

# ── Helpers ──────────────────────────────────────────────────────────────────

dir_has_sources() {
    local dir="$1" ext files
    for ext in "${SOURCE_EXTS[@]}"; do
        shopt -s nullglob; files=( "$dir"/$ext ); shopt -u nullglob
        [[ ${#files[@]} -gt 0 ]] && return 0
    done
    return 1
}

dir_has_vhdl() {
    local dir="$1" ext files
    for ext in "${VHDL_EXTS[@]}"; do
        shopt -s nullglob; files=( "$dir"/$ext ); shopt -u nullglob
        [[ ${#files[@]} -gt 0 ]] && return 0
    done
    return 1
}

dir_is_excluded() {
    local dir="$1" rel pattern
    rel="${dir#$ROOT/}"
    for pattern in "${EXCLUDE_PATTERNS[@]}"; do
        [[ "/$rel/" == *"/$pattern/"* || "$rel" == "$pattern" || "$rel" == "$pattern/"* ]] && return 0
    done
    return 1
}

# ── Generate Makefile.mk ─────────────────────────────────────────────────────
# The VHDL_SRCS block uses .compile_order when present (explicit order) and
# falls back to $(wildcard) otherwise.  Both branches are always emitted so
# the file is identical regardless of whether .compile_order exists yet.
generate_makefile_mk() {
    local dir="$1"
    local outfile="$dir/Makefile.mk"

    local content
    content=$(cat <<'TEMPLATE'
# ==============================================================================
# Auto-generated by scripts/scan_project.sh — DO NOT EDIT manually.
# Delete with 'make distclean' and regenerate with 'make scan'.
#
# C / C++ / Verilog / ASM source lists refresh via $(wildcard) on every 'make'.
# VHDL uses .compile_order when present (see below), wildcard otherwise.
# Re-run 'make scan' only when a NEW source directory is added.
# ==============================================================================

# Capture this file's directory at include time (standard GNU make idiom)
_THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

# ── C sources ─────────────────────────────────────────────────────────────────
C_SRCS    += $(wildcard $(_THIS_DIR)*.c)

# ── C++ sources ───────────────────────────────────────────────────────────────
CXX_SRCS  += $(wildcard $(_THIS_DIR)*.cpp $(_THIS_DIR)*.cxx $(_THIS_DIR)*.cc)

# ── VHDL sources ──────────────────────────────────────────────────────────────
# VHDL compilation order matters: packages must precede their users, entities
# must precede their instantiators.  Create/edit .compile_order (one filename
# per line, no paths) to control order.  The toolchain makefiles also run a
# silent pre-pass to auto-resolve simple out-of-order cases.
ifneq ($(wildcard $(_THIS_DIR).compile_order),)
# .compile_order found — use explicit order (strips # comments and blank lines)
VHDL_SRCS += $(addprefix $(_THIS_DIR),\
    $(shell grep -v '^[[:space:]]*#' '$(_THIS_DIR).compile_order' \
            | grep -v '^[[:space:]]*$$'))
else
# No .compile_order — alphabetical fallback (run 'make scan' to create one)
VHDL_SRCS += $(wildcard $(_THIS_DIR)*.vhd $(_THIS_DIR)*.vhdl)
endif

# ── Verilog / SystemVerilog sources ───────────────────────────────────────────
V_SRCS    += $(wildcard $(_THIS_DIR)*.v $(_THIS_DIR)*.sv)

# ── Assembly sources ──────────────────────────────────────────────────────────
ASM_SRCS  += $(wildcard $(_THIS_DIR)*.s $(_THIS_DIR)*.S $(_THIS_DIR)*.asm)
TEMPLATE
)

    if [[ -f "$outfile" ]]; then
        if [[ "$(cat "$outfile")" == "$content" ]]; then
            (( MK_SKIPPED++ )) || true
            return
        fi
        printf '%s\n' "$content" > "$outfile"
        info "Updated:  ${outfile#$ROOT/}"
        (( MK_UPDATED++ )) || true
    else
        printf '%s\n' "$content" > "$outfile"
        info "Created:  ${outfile#$ROOT/}"
        (( MK_CREATED++ )) || true
    fi
}

# ── Generate .compile_order ──────────────────────────────────────────────────
# Created once for VHDL directories; NEVER overwritten so user edits survive
# rescans.  Lists .vhd/.vhdl files alphabetically as a starting point.
generate_compile_order() {
    local dir="$1"
    local order_file="$dir/.compile_order"

    # Preserve existing file (user may have manually ordered it)
    if [[ -f "$order_file" ]]; then
        (( ORD_SKIPPED++ )) || true
        return
    fi

    local rel_dir="${dir#$ROOT/}"
    local vhdl_files=()
    shopt -s nullglob
    vhdl_files=( "$dir"/*.vhd "$dir"/*.vhdl )
    shopt -u nullglob

    {
        printf '# VHDL compilation order for: %s\n' "${rel_dir:-$(basename "$dir")}"
        printf '# Generated by scan_project.sh — edit freely, never overwritten by rescan.\n'
        printf '#\n'
        printf '# List one filename per line (no directory path), in compilation order.\n'
        printf '# Rule: a package or entity must appear BEFORE any file that uses it.\n'
        printf '#   e.g. if top.vhd instantiates counter, list counter.vhd first.\n'
        printf '# Lines starting with # and blank lines are ignored.\n'
        printf '#\n'
        printf '# Current files (alphabetical — reorder as needed):\n'
        for f in "${vhdl_files[@]}"; do
            printf '%s\n' "$(basename "$f")"
        done
    } > "$order_file"

    info "Created:  ${order_file#$ROOT/}  ← edit to set VHDL compilation order"
    (( ORD_CREATED++ )) || true
}

# ── Main scan ────────────────────────────────────────────────────────────────

log "Scanning: $ROOT"
log "──────────────────────────────────────────────────────"

while IFS= read -r -d '' dir; do
    dir_is_excluded "$dir" && continue
    if dir_has_sources "$dir"; then
        generate_makefile_mk "$dir"
        dir_has_vhdl "$dir" && generate_compile_order "$dir"
    fi
done < <(find "$ROOT" -type d -print0 | sort -z)

log "──────────────────────────────────────────────────────"
log "Makefile.mk  — Created: $MK_CREATED  Updated: $MK_UPDATED  Unchanged: $MK_SKIPPED"
log ".compile_order — Created: $ORD_CREATED  Unchanged (preserved): $ORD_SKIPPED"
log "Done."
