@echo off
REM ==============================================================================
REM scan_project.bat - Scan project tree and generate Makefile.mk files (Windows)
REM
REM Usage:  scripts\scan_project.bat [root_dir]
REM
REM For each directory that contains recognised source files the script creates
REM (or updates) a Makefile.mk that uses GNU make $(wildcard ...) so source
REM lists refresh automatically on every 'make' invocation.
REM
REM Re-run (or 'make scan') only when a NEW source directory is added.
REM ==============================================================================

setlocal enabledelayedexpansion

set "ROOT=%~1"
if "!ROOT!"=="" set "ROOT=."

set CREATED=0
set UPDATED=0
set SKIPPED=0

echo [SCAN] Scanning: !ROOT!
echo [SCAN] --------------------------------------------------------

REM Walk every directory under ROOT
for /R "!ROOT!" %%D in (.) do (
    set "DIR=%%~fD"
    set "HAS_SOURCES=0"
    set "SKIP=0"

    REM --- Exclude unwanted directories ---
    echo !DIR! | findstr /I /C:"\.git" /C:"\build" /C:"\make" /C:"\templates" /C:"\scripts" /C:"__pycache__" /C:"node_modules" >NUL 2>&1
    if not errorlevel 1 set "SKIP=1"

    if "!SKIP!"=="0" (
        REM --- Check for recognised source file extensions ---
        if exist "%%D\*.c"    set HAS_SOURCES=1
        if exist "%%D\*.cpp"  set HAS_SOURCES=1
        if exist "%%D\*.cxx"  set HAS_SOURCES=1
        if exist "%%D\*.cc"   set HAS_SOURCES=1
        if exist "%%D\*.vhd"  set HAS_SOURCES=1
        if exist "%%D\*.vhdl" set HAS_SOURCES=1
        if exist "%%D\*.v"    set HAS_SOURCES=1
        if exist "%%D\*.sv"   set HAS_SOURCES=1
        if exist "%%D\*.s"    set HAS_SOURCES=1
        if exist "%%D\*.S"    set HAS_SOURCES=1
        if exist "%%D\*.asm"  set HAS_SOURCES=1
    )

    if "!HAS_SOURCES!"=="1" (
        call :WriteMakefileMk "!DIR!"
    )
)

echo [SCAN] --------------------------------------------------------
echo [SCAN] Created: !CREATED!  ^|  Updated: !UPDATED!  ^|  Unchanged: !SKIPPED!
echo [SCAN] Done.
endlocal
goto :EOF

REM ==============================================================================
REM :WriteMakefileMk <dir>
REM   Writes a Makefile.mk to <dir> using PowerShell here-string so that
REM   GNU make variable syntax $(…) is preserved verbatim.
REM ==============================================================================
:WriteMakefileMk
setlocal
set "TARGET_DIR=%~1"
set "OUTFILE=%TARGET_DIR%\Makefile.mk"

REM Use PowerShell to write the file content — avoids cmd.exe escaping issues
REM with parentheses and dollar signs in make variable syntax.
powershell -NoProfile -Command ^
    "$content = @'" & ^
    "# ==============================================================================" & ^
    "# Auto-generated by scripts/scan_project.bat -- DO NOT EDIT manually." & ^
    "# Delete with 'make distclean' and regenerate with 'make scan'." & ^
    "#" & ^
    "# Source lists refresh automatically on every 'make' invocation via $(wildcard)." & ^
    "# Re-run 'make scan' only when a new source DIRECTORY is added." & ^
    "# ==============================================================================" & ^
    "" & ^
    "# Capture this file's directory at include time" & ^
    "_THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))" & ^
    "" & ^
    "# C sources" & ^
    "C_SRCS    += $(wildcard $(_THIS_DIR)*.c)" & ^
    "" & ^
    "# C++ sources" & ^
    "CXX_SRCS  += $(wildcard $(_THIS_DIR)*.cpp $(_THIS_DIR)*.cxx $(_THIS_DIR)*.cc)" & ^
    "" & ^
    "# VHDL sources" & ^
    "VHDL_SRCS += $(wildcard $(_THIS_DIR)*.vhd $(_THIS_DIR)*.vhdl)" & ^
    "" & ^
    "# Verilog / SystemVerilog sources" & ^
    "V_SRCS    += $(wildcard $(_THIS_DIR)*.v $(_THIS_DIR)*.sv)" & ^
    "" & ^
    "# Assembly sources" & ^
    "ASM_SRCS  += $(wildcard $(_THIS_DIR)*.s $(_THIS_DIR)*.S $(_THIS_DIR)*.asm)" & ^
    "'@" & ^
    "$existing = if (Test-Path '%OUTFILE%') { Get-Content '%OUTFILE%' -Raw } else { '' }" & ^
    "if ($content.Trim() -eq $existing.Trim()) { exit 2 }" & ^
    "$content | Set-Content -Encoding UTF8 '%OUTFILE%'"

if errorlevel 3 (
    echo [SCAN]   Error writing: %OUTFILE%
) else if errorlevel 2 (
    set /A SKIPPED=!SKIPPED!+1
) else (
    if exist "%OUTFILE%" (
        echo [SCAN]   Updated:  %OUTFILE%
        set /A UPDATED=!UPDATED!+1
    ) else (
        echo [SCAN]   Created:  %OUTFILE%
        set /A CREATED=!CREATED!+1
    )
)
endlocal & set CREATED=%CREATED% & set UPDATED=%UPDATED% & set SKIPPED=%SKIPPED%
goto :EOF
