@echo off
REM ==============================================================================
REM scan_project.bat — Scan project tree and generate Makefile.mk files (Windows)
REM
REM Usage:  scripts\scan_project.bat [root_dir]
REM
REM For each directory with recognised source files the script:
REM   1. Creates/updates Makefile.mk  (VHDL_SRCS uses .compile_order if present)
REM   2. Creates .compile_order       (VHDL dirs only; NEVER overwritten)
REM
REM Requires PowerShell (available on Windows 7+) for file writing.
REM ==============================================================================

setlocal enabledelayedexpansion

set "ROOT=%~1"
if "!ROOT!"=="" set "ROOT=."

set MK_CREATED=0
set MK_UPDATED=0
set MK_SKIPPED=0
set ORD_CREATED=0
set ORD_SKIPPED=0

echo [SCAN] Scanning: !ROOT!
echo [SCAN] --------------------------------------------------------

for /R "!ROOT!" %%D in (.) do (
    set "DIR=%%~fD"
    set "HAS_SOURCES=0"
    set "HAS_VHDL=0"
    set "SKIP=0"

    echo !DIR! | findstr /I /C:"\.git" /C:"\build" /C:"\make" /C:"\templates" /C:"\scripts" /C:"__pycache__" /C:"node_modules" >NUL 2>&1
    if not errorlevel 1 set "SKIP=1"

    if "!SKIP!"=="0" (
        if exist "%%D\*.c"    set HAS_SOURCES=1
        if exist "%%D\*.cpp"  set HAS_SOURCES=1
        if exist "%%D\*.cxx"  set HAS_SOURCES=1
        if exist "%%D\*.cc"   set HAS_SOURCES=1
        if exist "%%D\*.vhd"  set HAS_SOURCES=1 & set HAS_VHDL=1
        if exist "%%D\*.vhdl" set HAS_SOURCES=1 & set HAS_VHDL=1
        if exist "%%D\*.v"    set HAS_SOURCES=1
        if exist "%%D\*.sv"   set HAS_SOURCES=1
        if exist "%%D\*.s"    set HAS_SOURCES=1
        if exist "%%D\*.S"    set HAS_SOURCES=1
        if exist "%%D\*.asm"  set HAS_SOURCES=1
    )

    if "!HAS_SOURCES!"=="1" (
        call :WriteMakefileMk "!DIR!"
        if "!HAS_VHDL!"=="1" call :WriteCompileOrder "!DIR!"
    )
)

echo [SCAN] --------------------------------------------------------
echo [SCAN] Makefile.mk    -- Created: !MK_CREATED!  Updated: !MK_UPDATED!  Unchanged: !MK_SKIPPED!
echo [SCAN] .compile_order -- Created: !ORD_CREATED!  Unchanged ^(preserved^): !ORD_SKIPPED!
echo [SCAN] Done.
endlocal
goto :EOF

REM ==============================================================================
REM :WriteMakefileMk <dir>
REM ==============================================================================
:WriteMakefileMk
setlocal
set "TARGET_DIR=%~1"
set "OUTFILE=%TARGET_DIR%\Makefile.mk"

powershell -NoProfile -Command ^
    "$c = @'" & ^
    "# ==============================================================================" & ^
    "# Auto-generated by scripts/scan_project.bat -- DO NOT EDIT manually." & ^
    "# C/C++/Verilog/ASM use $(wildcard). VHDL uses .compile_order if present." & ^
    "# ==============================================================================" & ^
    "" & ^
    "_THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))" & ^
    "" & ^
    "C_SRCS    += $(wildcard $(_THIS_DIR)*.c)" & ^
    "CXX_SRCS  += $(wildcard $(_THIS_DIR)*.cpp $(_THIS_DIR)*.cxx $(_THIS_DIR)*.cc)" & ^
    "" & ^
    "ifneq ($(wildcard $(_THIS_DIR).compile_order),)" & ^
    "VHDL_SRCS += $(addprefix $(_THIS_DIR),\" & ^
    "    $(shell grep -v '^[[:space:]]*#' '$(_THIS_DIR).compile_order' \" & ^
    "            | grep -v '^[[:space:]]*$$'))" & ^
    "else" & ^
    "VHDL_SRCS += $(wildcard $(_THIS_DIR)*.vhd $(_THIS_DIR)*.vhdl)" & ^
    "endif" & ^
    "" & ^
    "V_SRCS    += $(wildcard $(_THIS_DIR)*.v $(_THIS_DIR)*.sv)" & ^
    "ASM_SRCS  += $(wildcard $(_THIS_DIR)*.s $(_THIS_DIR)*.S $(_THIS_DIR)*.asm)" & ^
    "'@" & ^
    "$e = if (Test-Path '%OUTFILE%') { Get-Content '%OUTFILE%' -Raw } else { '' }" & ^
    "if ($c.Trim() -eq $e.Trim()) { exit 2 }" & ^
    "$c | Set-Content -Encoding UTF8 '%OUTFILE%'"

if errorlevel 3 (
    echo [SCAN]   Error writing Makefile.mk in %TARGET_DIR%
) else if errorlevel 2 (
    set /A MK_SKIPPED=!MK_SKIPPED!+1
) else (
    echo [SCAN]   Makefile.mk  Created/Updated: %TARGET_DIR%
    set /A MK_CREATED=!MK_CREATED!+1
)
endlocal & set MK_CREATED=%MK_CREATED% & set MK_UPDATED=%MK_UPDATED% & set MK_SKIPPED=%MK_SKIPPED%
goto :EOF

REM ==============================================================================
REM :WriteCompileOrder <dir>  — Creates .compile_order; NEVER overwrites
REM ==============================================================================
:WriteCompileOrder
setlocal
set "TARGET_DIR=%~1"
set "OUTFILE=%TARGET_DIR%\.compile_order"

if exist "%OUTFILE%" (
    set /A ORD_SKIPPED=!ORD_SKIPPED!+1
    endlocal & set ORD_SKIPPED=%ORD_SKIPPED%
    goto :EOF
)

REM Build file list via PowerShell
powershell -NoProfile -Command ^
    "$dir = '%TARGET_DIR%';" ^
    "$files = (Get-ChildItem -Path $dir -Filter '*.vhd','*.vhdl' -File | Sort Name | ForEach-Object { $_.Name }) -join [Environment]::NewLine;" ^
    "$header = '# VHDL compilation order for: %TARGET_DIR%' + [Environment]::NewLine +" ^
    "          '# Generated by scan_project.bat -- edit freely, never overwritten.' + [Environment]::NewLine +" ^
    "          '#' + [Environment]::NewLine +" ^
    "          '# One filename per line (no path), in compilation order.' + [Environment]::NewLine +" ^
    "          '# Rule: list packages/entities BEFORE any file that uses them.' + [Environment]::NewLine +" ^
    "          '# Lines starting with # and blank lines are ignored.' + [Environment]::NewLine +" ^
    "          '#' + [Environment]::NewLine +" ^
    "          '# Current files (alphabetical -- reorder as needed):' + [Environment]::NewLine;" ^
    "($header + $files) | Set-Content -Encoding UTF8 '%OUTFILE%'"

echo [SCAN]   .compile_order Created: %OUTFILE%  ^<-- edit to set VHDL order
set /A ORD_CREATED=!ORD_CREATED!+1
endlocal & set ORD_CREATED=%ORD_CREATED% & set ORD_SKIPPED=%ORD_SKIPPED%
goto :EOF
