# ==============================================================================
# gcc.mk — GNU C Compiler toolchain rules
# Handles: .c source files → binary or static library
# ==============================================================================

# Derive object files, preserving directory structure under BUILD_DIR
C_OBJS := $(patsubst %.c,$(BUILD_DIR)/%.o,$(C_SRCS))

# Dependency files (auto-generated by -MMD -MP)
DEPS := $(C_OBJS:.o=.d)
-include $(DEPS)

# Propagate include directories and enable dependency tracking
CFLAGS += $(addprefix -I,$(INC_DIRS)) -MMD -MP

.PHONY: all

all: $(BUILD_DIR)/$(PROJECT_NAME)

# ── Link ──────────────────────────────────────────────────────────────────────
$(BUILD_DIR)/$(PROJECT_NAME): $(C_OBJS)
	@echo "[LD]  $@"
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

# ── Compile ───────────────────────────────────────────────────────────────────
$(BUILD_DIR)/%.o: %.c
	@echo "[CC]  $<"
	@$(MKDIR) $(dir $@)
	$(CC) $(CFLAGS) -c -o $@ $<

$(BUILD_DIR):
	$(MKDIR) $@
